version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the docker image...
      - docker build --rm=false -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME:latest 349501831018.dkr.ecr.us-west-2.amazonaws.com/$IMAGE_NAME:latest
  post_build:
    commands :
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 349501831018.dkr.ecr.us-west-2.amazonaws.com/$IMAGE_NAME:latest 
      - echo updating ecs service....
      - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
      - echo Done updating ecs

       