

.PHONEY: init build test

init:
	@echo "Init CI Build..."
	sh scripts/init.sh

build:
	@echo "Building..."
	. ~/.nvm/nvm.sh && nvm use 8.4.0 && make build

test:
	@echo "Testing..."
	npm run test -- -u --testPathIgnorePatterns=dist
