

.PHONEY: init build test


init:
	@echo "Init CI Build..."
	nvm install 4.4.3
	nvm use 4.4.3
	npm install npm -g
	npm config set registry http://registry.npmjs.org/
	npm cache clean
	npm install
	# Install grunt-cli for running your tests or other tasks
	npm install -g grunt-cli bower@1.7.2 karma
	npm install sass
	bower install

build: init
	@echo "Building..."
	grunt

test:
	@echo "Testing..."
	@echo "Not really"

