export { BLACK as EXTREME} from 'constants/forecast/palette'
export { RED as HIGH} from 'constants/forecast/palette'
export { ORANGE as CONSIDERABLE} from 'constants/forecast/palette'
export { YELLOW as MODERATE} from 'constants/forecast/palette'
export { GREEN as LOW} from 'constants/forecast/palette'
export { WHITE as NO_RATING} from 'constants/forecast/palette'
