export { RED as EXTREME} from 'constants/forecast/palette'
export { BLACK as HIGH} from 'constants/forecast/palette'
export { BLACK as CONSIDERABLE} from 'constants/forecast/palette'
export { BLACK as MODERATE} from 'constants/forecast/palette'
export { BLACK as LOW} from 'constants/forecast/palette'
export { BLACK as NO_RATING} from 'constants/forecast/palette'
