export default new Map([
    ['/events/VvLeBSUAAJgDAgX6', '/events/asa-snowmobile-show-2016'],
    ['/events/V-r2XyYAACcAblCX', '/events/spin-safety-fundraiser'],
    ['/events/VEFS_yYAACYARWyK', '/events/thunderstuck-fundraiser-2016'],
    ['/events/V9bxeiYAACgA9jex', '/events/cardel-homes-movie-ruin-rose'],
    ['/events/V9By4yYAACgAz0Ni', '/events/agm-save-the-date-2016'],
    ['/events/V7Sy6ycAACUAo4u_', '/events/bcsnowmobileshow_2016'],
    ['/events/Vmdqex4AAB0AxBYc', '/events/youth-snow-safety-phoenixmnt-2016'],
    ['/events/VnCZbR8AAFYKrNgo', '/events/aad-kananaskis-jan-2016'],
    ['/events/VoQjoR8AADZzIjEZ', '/events/aad-whitewater-jan-2016'],
    ['/events/VnCX1h8AAFYKrM88', '/events/lake-louise-staying-alive-2016'],
    ['/events/VliqsR0AAOcTy0Ig', '/events/aad-general-announcement-2016'],
    ['/events/VpfKah8AAI1FMEHK', '/events/aad-mtseymour-jan-2016'],
    ['/events/Vpf4ACMAACQAX8yN', '/events/aad-bouldermnt-revelstoke-2016'],
    ['/events/VsukNiMAACwavKfV', '/events/shreducation-yukon-feb-2016'],
    ['/events/VmdsER4AAPYJxB90', '/events/aad-lake-louise-2016'],
    ['/events/VoQkah8AAEZvIjSt', '/events/aad-khmr-jan-2016'],
    ['/events/VlyuDyUAACUAnMJ-', '/events/baw-fernie-jan-2016'],
    ['/events/Vo1p7yIAAMcFB2W7', '/events/aad-rossland-jan-2016'],
    ['/events/VpfMIx8AAKlFMEwl', '/events/aad-crowsnestpass-jan-2016'],
    ['/events/Vp1xcSYAACUAQUbq', '/events/aad-mtsima-jan-2016'],
    ['/events/VlywoyUAACQAnNG8', '/events/shreducation-revelstoke-jan-2016'],
    [
        '/events/VvHBBCwAAAisDiFM',
        '/events/avalanche-rescue-challenge-stewart-2016',
    ],
    [
        '/events/VvLUTCUAAMEAAc3N',
        '/events/saskatchewan-snowmobile-show-nov-2016',
    ],
    ['/events/VnCWSR8AAMoKrMX6', '/events/aad-garibaldi-jan-2016'],
    ['/events/VpRUhx8AABsHG57y', '/events/aad-kakwa-feb-2016'],
    [
        '/events/VpfOKCMAACIAXtdX',
        '/events/rumrunner-cherrybowl-presentation-2016',
    ],
    ['/events/VrJnQisAAGMj2Y_U', '/events/ascend-splitboard-fest-2016'],
    ['/events/VrpuBSgAAEIC5kXJ', '/events/acc-cherrybowl-presentation-2016'],
    ['/events/VK8DjSMAACUANEm1', '/events/foundation-calgary-fundraiser-2016'],
    ['/events/VvBrrywAAHOKBjIg', '/events/bcsf-agm-pemberton-2016'],
    ['/events/VkTj0CAAAB8AKQs5', '/events/staying-alive-khmr-dec-2015'],
    ['/events/VmdlSR4AAAMNw_cW', '/events/aad-mt-cain-feb-2016'],
    ['/events/VoQlZx8AAEZvIjpK', '/events/aad-fernie-alpine-resort-2016'],
    ['/events/VownoR8AAIinUi2W', '/events/aad-apex-jan-2016'],
    ['/events/VpRSkB8AAOELG5N2', '/events/aad-whistler-jan-2016'],
    ['/events/VpmCByMAAFUcaOGm', '/events/aad-rmr-jan-2016'],
    ['/events/VqkoRSQAACUAbEwW', '/events/youth-sled-day-revelstoke-2016'],
    ['/events/VvLCACUAAMEAAWBL', '/events/avcan-agm-vancouver-fall-2016'],
    [
        '/events/VyE6eiYAAJURUa72',
        '/events/caa-spring-conference-case-studies-2016',
    ],
    ['/events/VvF1CSwAAGKgDF2C', '/events/issw-2016-breckenridge'],
    ['/events/Vmdhxx4AAAQNw-Jb', '/events/aad-banff-jan-2016'],
    ['/events/Vqfpwh4AACMAso45', '/events/aad-smithers-2016'],
    ['/events/VvB06CwAAIqKBmhf', '/events/isc-2016-snowmobile'],
    ['/news/V-r0EyYAACcAbkKw', '/news/register-now'],
    [
        '/news/V8hpNyQAABuEOE6V',
        '/news/avalanche-canada-has-brand-new-youth-tool-boxes-available',
    ],
    ['/news/V9Br8SYAACcAzxmI', '/news/calgary-foundation-grant-award'],
    ['/news/Vow8-R8AAFDJUq1b', '/news/transceiver-interference'],
    ['/news/VEV1hyYAAKwITagl', '/news/annual-report-2014'],
    ['/news/VIDCKCsAACcAgEpK', '/news/donation-request-avalanche-canada'],
    [
        '/news/VL63mCUAACYAOeVo',
        '/news/canuck-splitfest-fundraiser-success-2015',
    ],
    ['/news/VL7ZgiUAACMAOilw', '/news/thunderstruck-fundraiser-donation-2015'],
    [
        '/news/VNASWCUAAJQpqGrY',
        '/news/deep-winter-photo-challenge-fundraiser-2015',
    ],
    ['/news/VT_rPiYAACUAbasG', '/news/mountain-weather-forecast-summer'],
    ['/news/VftedR8AAIYAI8QW', '/news/acc-new-hut'],
    ['/news/ViGKDCEAAEwWNpIz', '/news/agm-2015'],
    ['/news/VHZlwSgAACYAw466', '/news/boundary-changes-south-rockies'],
    [
        '/news/VH-XbykAACwAQbtc',
        '/news/arcteryx-deep-winter-photo-challenge-2014',
    ],
    ['/news/VJIKXCcAACYAFiD-', '/news/avalanche-awareness-days-2015'],
    [
        '/news/VLbN0CMAALqmQ9tp',
        '/news/introduction-mountain-information-network',
    ],
    ['/news/VRmZzR8AAOIMXMnP', '/news/agm-october-announcement'],
    ['/news/VZ7psx0AAB0AuUBl', '/news/recall-bd-jetforce-airbag'],
    ['/news/ViauYB0AAHAHUPr_', '/news/new-support-craig-kelly-fund'],
    ['/news/ViayAx0AAB4AURDZ', '/news/cora-shea-memorial-awards'],
    ['/news/VkDizCEAAJsBkh2d', '/news/bca-backcountry-basics-videos'],
    ['/news/VDbtkScAAKUBPZm5', '/news/introducing-avalanche-canada'],
    ['/news/VH5GLSMAACcAc0vA', '/news/snorider-brent-strand-announcement'],
    ['/news/VIockywAACsA-wP3', '/news/forecasts-inbox-rss'],
    [
        '/news/VL6NXiUAACYAOZA3',
        '/news/announcement-new-mountain-weather-forecast',
    ],
    ['/news/VP9AZR4AACQAlToR', '/news/land-thundering-snow-launch'],
    ['/news/VRrR-x8AAKBCX0JI', '/news/recall-ortovox-s1'],
    ['/news/VQh-RikAACgA6K4B', '/news/calgary-fundraiser-success-2015'],
    ['/news/VdNwyB8AAE4Ln13g', '/news/al-hodgson-memorial-fund'],
    ['/news/VEbXGiYAACsAaNZV', '/news/five-snowmobile-safety-messages'],
    ['/news/VEbHaSYAACsAaLc_', '/news/tedx-talk-risk'],
    ['/news/VH-KSykAACkAQaCR', '/news/baw-success-2014'],
    ['/news/VIivUisAACYAY0tp', '/news/avalanche-canada-widget-update'],
    ['/news/VIoEBSwAACsA-tKL', '/news/dramatic-rescue-clemina-creek'],
    ['/news/VEVy9CYAACQATaL-', '/news/justin-trudeau-message'],
    ['/news/VVtiryYAAOwJxyOO', '/news/recall-msr-snow-shovels'],
    ['/news/VMgrmyUAAJQpmL6o', '/news/min-how-to-videos'],
    ['/news/VjkZEB0AAB0AV7J4', '/news/annual-report-2015'],
    ['/news/VkogLh8AAB0AI-ag', '/news/free-ast-youth-course-fernie'],
    ['/news/Vk4VIh4AAG8G0bZg', '/news/new-sponsor-g3'],
    ['/news/VlN8siIAAFANmCkM', '/news/new-release-throttle-decisions'],
    ['/news/VlYciR0AADgEB1Sp', '/news/cross-border-collaboration-training'],
    ['/news/VpPu3h8AAKAFGUI2', '/news/avalanche-awareness-days-primer'],
    ['/news/VrOc4CsAACwA4KjU', '/news/pr-bc-coroner-avalanche-feb3'],
    ['/news/VrjoXiYAAEwCjmRs', '/news/avalanche-ambassador-aad-revelstoke'],
    ['/news/VN0YqSYAACoAJakp', '/news/membership-drive'],
    ['/news/Vst0dyMAADoSu4_N', '/news/al-hodgson-memorial-award'],
    ['/news/Vplv7SMAAFQcaHWb', '/news/sfu-new-research-chair'],
    ['/news/VpV_lx8AAMUSIpac', '/news/min-update'],
    ['/news/VuxMXiwAALFL7Yyb', '/news/foundation-calgary-benefit-2016'],
    ['/news/VjukhiMAACQA2fJX', '/news/new-office-space'],
    ['/news/VnHASR8AAIoSs8eR', '/news/thunderstruck-rsc-fundraiser'],
    ['/news/Vw6XMCkAAD9f09uB', '/news/craig-kelly-scholarship-awarded'],
    ['/news/Vx-6kSkAAEG1OTEL', '/news/hot-zone-reports'],
    ['/news/Vk0CliEAAKIFhX3l', '/news/2015-service-award'],
    [
        '/news/Vh1iVx4AALsES5Zw',
        '/news/avalanche-ambassador-program-announcement',
    ],
    ['/news/VyeeSiYAAASDd20a', '/news/land-of-thundering-snow'],
    ['/news/VpP3lB8AAKAFGXVS', '/news/canuck-splitfest-2016'],
    ['/news/VK7R4iMAACMAM93b', '/news/snowmobile-loaners-2016'],
    ['/news/VuhTEiwAAMEK1gWI', '/news/adjunct-professor-announcement'],
    ['/news/Vw_rICkAALuO27JE', '/news/royal-canadian-pacific-fundraiser'],
    ['/cac/training/ast/courses', '/training/courses'],
    ['/cac/training/overview', '/training'],
    ['/cac/training/online-course', '/tutorial'],
    ['/cac', '/'],
    // Redirect for links between documents
    ['/pages/static-page/sled', '/sled'],
    ['/pages/static-page/youth', '/youth'],
    ['/pages/static-page/essential-gear', '/gear'],
    ['/pages/static-page/training', '/training'],
    [
        '/pages/static-page/mountain-information-network-overview',
        '/mountain-information-network',
    ],
    [
        '/pages/static-page/mountain-information-network-submission-guidelines',
        '/mountain-information-network/submission-guidelines',
    ],
    ['/pages/static-page/about', '/about'],
    [
        '/pages/static-page/mountain-information-network-faq',
        '/mountain-information-network/faq',
    ],
    ['/pages/static-page/ambassadors', '/ambassadors'],
    ['/pages/static-page/sponsors', '/sponsors'],
    ['/pages/static-page/collaborators', '/collaborators'],
    ['/pages/static-page/membership-overview', '/membership'],
    ['/generic/privacy-policy', 'privacy-policy'],
    ['/generic/terms-of-use', 'terms-of-use'],
    ['/generic/auction', 'auction'],
    ['/cherrybowl', 'cherry-bowl'],
    ['/min', '/mountain-information-network'],
    ['/min/submit', '/mountain-information-network/submit'],
    ['/min/faq', '/mountain-information-network/faq'],
    [
        '/min/submission-guidelines',
        '/mountain-information-network/submission-guidelines',
    ],
    ['/min/submissions/:id', '/mountain-information-network/submissions/:id'],
    ['/min/submissions', '/mountain-information-network/submissions'],
    [
        '/pages/static-page/mountain-information-network-faq',
        '/mountain-information-network/faq',
    ],
    [
        '/pages/static-page/mountain-information-network-submission-guidelines',
        '/mountain-information-network/submission-guidelines',
    ],
    ['/learn', '/training'],
    ['/forecast/:name', '/forecasts/:name'],
    ['/submit', '/mountain-information-network/submit'],
])
