export const EXTREME = '5 - Extreme'
export const HIGH = '4 - High'
export const CONSIDERABLE = '3 - Considerable'
export const MODERATE = '2 - Moderate'
export const LOW = '1 - Low'
export const NO_RATING = '0 - No Rating'
