import {normalize, arrayOf} from 'normalizr'
import * as Schemas from 'api/schemas'
import {createApiAction, createPostAction} from 'api/utils'

export const FORECAST_REQUEST = 'FORECAST_REQUEST'
export const FORECAST_SUCCESS = 'FORECAST_SUCCESS'
export const FORECAST_FAILURE = 'FORECAST_FAILURE'

export const FORECAST_REGIONS_REQUEST = 'FORECAST_REGIONS_REQUEST'
export const FORECAST_REGIONS_SUCCESS = 'FORECAST_REGIONS_SUCCESS'
export const FORECAST_REGIONS_FAILURE = 'FORECAST_REGIONS_FAILURE'

export const HOT_ZONE_AREAS_REQUEST = 'HOT_ZONE_AREAS_REQUEST'
export const HOT_ZONE_AREAS_SUCCESS = 'HOT_ZONE_AREAS_SUCCESS'
export const HOT_ZONE_AREAS_FAILURE = 'HOT_ZONE_AREAS_FAILURE'

export const HOT_ZONE_REPORTS_REQUEST = 'HOT_ZONE_REPORTS_REQUEST'
export const HOT_ZONE_REPORTS_SUCCESS = 'HOT_ZONE_REPORTS_SUCCESS'
export const HOT_ZONE_REPORTS_FAILURE = 'HOT_ZONE_REPORTS_FAILURE'

export const MOUNTAIN_INFORMATION_NETWORK_SUBMISSIONS_REQUEST = 'MOUNTAIN_INFORMATION_NETWORK_SUBMISSIONS_REQUEST'
export const MOUNTAIN_INFORMATION_NETWORK_SUBMISSIONS_SUCCESS = 'MOUNTAIN_INFORMATION_NETWORK_SUBMISSIONS_SUCCESS'
export const MOUNTAIN_INFORMATION_NETWORK_SUBMISSIONS_FAILURE = 'MOUNTAIN_INFORMATION_NETWORK_SUBMISSIONS_FAILURE'

export const MOUNTAIN_INFORMATION_NETWORK_SUBMISSION_REQUEST = 'MOUNTAIN_INFORMATION_NETWORK_SUBMISSION_REQUEST'
export const MOUNTAIN_INFORMATION_NETWORK_SUBMISSION_SUCCESS = 'MOUNTAIN_INFORMATION_NETWORK_SUBMISSION_SUCCESS'
export const MOUNTAIN_INFORMATION_NETWORK_SUBMISSION_FAILURE = 'MOUNTAIN_INFORMATION_NETWORK_SUBMISSION_FAILURE'

export const POST_MOUNTAIN_INFORMATION_NETWORK_SUBMISSION_REQUEST = 'POST_MOUNTAIN_INFORMATION_NETWORK_SUBMISSION_REQUEST'
export const POST_MOUNTAIN_INFORMATION_NETWORK_SUBMISSION_SUCCESS = 'POST_MOUNTAIN_INFORMATION_NETWORK_SUBMISSION_SUCCESS'
export const POST_MOUNTAIN_INFORMATION_NETWORK_SUBMISSION_FAILURE = 'POST_MOUNTAIN_INFORMATION_NETWORK_SUBMISSION_FAILURE'

export const INCIDENTS_REQUEST = 'INCIDENTS_REQUEST'
export const INCIDENTS_SUCCESS = 'INCIDENTS_SUCCESS'
export const INCIDENTS_FAILURE = 'INCIDENTS_FAILURE'

export const PROVIDERS_REQUEST = 'PROVIDERS_REQUEST'
export const PROVIDERS_SUCCESS = 'PROVIDERS_SUCCESS'
export const PROVIDERS_FAILURE = 'PROVIDERS_FAILURE'

export const COURSES_REQUEST = 'COURSES_REQUEST'
export const COURSES_SUCCESS = 'COURSES_SUCCESS'
export const COURSES_FAILURE = 'COURSES_FAILURE'

export const WEATHER_STATIONS_REQUEST = 'WEATHER_STATIONS_REQUEST'
export const WEATHER_STATIONS_SUCCESS = 'WEATHER_STATIONS_SUCCESS'
export const WEATHER_STATIONS_FAILURE = 'WEATHER_STATIONS_FAILURE'

export const loadForecastRegions = createApiAction(
    Schemas.ForecastRegion,
    FORECAST_REGIONS_REQUEST,
    FORECAST_REGIONS_SUCCESS,
    FORECAST_REGIONS_FAILURE,
)

export const loadForecast = createApiAction(
    Schemas.Forecast,
    FORECAST_REQUEST,
    FORECAST_SUCCESS,
    FORECAST_FAILURE,
)

export const loadHotZoneAreas = createApiAction(
    Schemas.HotZoneArea,
    HOT_ZONE_AREAS_REQUEST,
    HOT_ZONE_AREAS_SUCCESS,
    HOT_ZONE_AREAS_FAILURE,
)

export const loadHotZoneReports = createApiAction(
    Schemas.HotZoneReport,
    HOT_ZONE_REPORTS_REQUEST,
    HOT_ZONE_REPORTS_SUCCESS,
    HOT_ZONE_REPORTS_FAILURE,
)

const loadMountainInformationNetworkSubmissions = createApiAction(
    Schemas.MountainInformationNetworkSubmission,
    MOUNTAIN_INFORMATION_NETWORK_SUBMISSIONS_REQUEST,
    MOUNTAIN_INFORMATION_NETWORK_SUBMISSIONS_SUCCESS,
    MOUNTAIN_INFORMATION_NETWORK_SUBMISSIONS_FAILURE,
)

export function loadMountainInformationNetworkSubmissionsForDays(days = 7) {
    return loadMountainInformationNetworkSubmissions({days})
}

export function loadMountainInformationNetworkSubmission(id) {
    return loadMountainInformationNetworkSubmissions({id})
}

export const loadIncidents = createApiAction(
    Schemas.Incident,
    INCIDENTS_REQUEST,
    INCIDENTS_SUCCESS,
    INCIDENTS_FAILURE,
)

export const loadProviders = createApiAction(
    Schemas.Provider,
    PROVIDERS_REQUEST,
    PROVIDERS_SUCCESS,
    PROVIDERS_FAILURE,
)

export const loadCourses = createApiAction(
    Schemas.Course,
    COURSES_REQUEST,
    COURSES_SUCCESS,
    COURSES_FAILURE,
)

export const loadWeatherStations = createApiAction(
    Schemas.WeatherStation,
    WEATHER_STATIONS_REQUEST,
    WEATHER_STATIONS_SUCCESS,
    WEATHER_STATIONS_FAILURE,
)

export function loadWeatherStation(id) {
    return loadWeatherStations({id})
}

// CREATE ENTITY
export const postMountainInformationNetworkSubmission = createPostAction(
    Schemas.MountainInformationNetworkSubmission,
    POST_MOUNTAIN_INFORMATION_NETWORK_SUBMISSION_REQUEST,
    POST_MOUNTAIN_INFORMATION_NETWORK_SUBMISSION_SUCCESS,
    POST_MOUNTAIN_INFORMATION_NETWORK_SUBMISSION_FAILURE,
)
