#!/usr/bin/env node

var jwt = require('jsonwebtoken');

var args = process.argv.slice(2);

args.forEach(function(token){
    var profile = jwt.decode(token);
    console.log(profile);
    if (process.env.AUTH0_CLIENT_SECRET) {
        var sec = Buffer.from(process.env.AUTH0_CLIENT_SECRET, 'base64');
        try {
            var is_valid = jwt.verify(token, sec);
            console.log('Token valid: TRUE');
        } catch (err) {
            console.log('Token valid: FALSE ('+err.message+')');
        }
    } else {
        console.log('Token valid: Unknown (No secret key provided)');
    }
})

