export const FORECASTS = 'FORECASTS'
export const HOT_ZONE_REPORTS = 'HOT_ZONE_REPORTS'
export const MOUNTAIN_INFORMATION_NETWORK = 'MOUNTAIN_INFORMATION_NETWORK'
export const MOUNTAIN_INFORMATION_NETWORK_INCIDENTS =
    'MOUNTAIN_INFORMATION_NETWORK_INCIDENTS'
export const WEATHER_STATION = 'WEATHER_STATION'
export const TOYOTA_TRUCK_REPORTS = 'TOYOTA_TRUCK_REPORTS'
export const SPECIAL_INFORMATION = 'SPECIAL_INFORMATION'
export const FATAL_ACCIDENT = 'FATAL_ACCIDENT'
export const MOUNTAIN_CONDITIONS_REPORTS = 'MOUNTAIN_CONDITIONS_REPORTS'

export default [
    FORECASTS,
    HOT_ZONE_REPORTS,
    MOUNTAIN_INFORMATION_NETWORK,
    MOUNTAIN_INFORMATION_NETWORK_INCIDENTS,
    WEATHER_STATION,
    TOYOTA_TRUCK_REPORTS,
    SPECIAL_INFORMATION,
    FATAL_ACCIDENT,
    MOUNTAIN_CONDITIONS_REPORTS,
]
